eureka:
    instance:
        prefer-ip-address: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
              defaultZone: http://localhost:8761/eureka/
        instance:
              hostname: localhost

spring:
  application:
      name: CONFIG-DEV
